export RHSM_USER=<subscription username>
export RHSM_PASSWD=<subscription password>
export RHSM_POOL=<POOL ID for EMPLOYEE SKU>
export REG_USERNAME=<registry.redhat.io service account username>
export REG_TOKEN=<registry.redhat.io service account token>
export ENV_ID=<subdomain for this cluster>
export OCP_USERNAME=<cluster admin account>
export OCP_PASSWORD=<cluster admin password>
export IDM_DM_PASSWORD=<password here>
export IDM_ADMIN_PASSWORD=<password here>
