---
ansible_connection: local
openshift_cluster_content:
- object: ci-cd-tooling
  content:
  - name: "nexus"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/nexus.yml"
    params: "{{ playbook_dir }}/params/nexus"
    tags:
    - nexus
  - name: "jenkins-mongodb"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/mongodb.yml"
    params: "{{ playbook_dir }}/params/mongodb"
    tags:
    - mongodb
  - name: "jenkins"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/jenkins.yml"
    params: "{{ playbook_dir }}/params/jenkins"
    tags:
    - jenkins
  - name: "gitlab"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/gitlab.yml"
    params: "{{ playbook_dir }}/params/gitlab"
    tags:
    - gitlab
- object: ci-cd-builds
  content:
  - name: "jenkins-s2i"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/jenkins-s2i.yml"
    params: "{{ playbook_dir }}/params/jenkins-s2i"
    tags:
    - jenkins
- object: "Jenkins slave npm"
  content:
  - name: "jenkins-npm-slave"
    namespace: "openshift"
    template: "{{ playbook_dir }}/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slave-npm"
    tags:
    - jenkins-slave-npm
