---
ansible_user: ec2-user
ansible_become: True
ansible_ssh_private_key_file: ~/.ssh/glsdemo2.pem
idm_master_hostname: idm.labs.nextcle.com
idm_domain: labs.nextcle.com
idm_realm: labs.nextcle.com
idm_dm_password: D0ma1n123!
idm_admin_password: Adm1n123!
rhsm_username: "{{ lookup('env', 'RHSM_USER' )}}"
rhsm_password: "{{ lookup('env', 'RHSM_PASSWD' )}}"
rhsm_pool: "{{ lookup('env', 'RHSM_POOL' )}}"
rhsm_repos:
 - rhel-7-server-rpms
