== Introduction

=== DevOps Culture and Practice

Many organizations are making or want to make a shift towards a modern application
development and delivery model. This model, called DevOps, promises to provide
streams of new features in shorter delivery windows by employing techniques such
as Continuous Integration, Continuous Delivery, and Agile development practices.
Entering the world of digital transformation requires not only a technology shift
but a cultural shift.

_DevOps Culture and Practice_ (DO500),
provides the student an immersive experience of DevOps culture, modern software
development practices, and modern application development architectures.
Through team work the students engage in modern practices, experience a new
culture, and complete hands-on labs that deploy modern, containerized applications
featuring foundational DevOps principles and Red Hat OpenShift Container Platform.

=== Objectives
* Gain experience using various DevOps practices that will help the student in
their desire to transform the software development culture in their organization
* Apply DevOps practices and principles in the development of a simple web application
using Red Hat technologies
* TBD

=== Audience
* Software Developers
* Software Architects
* Product Owners
* Project Managers
* Business Analysts

=== Prerequisites
* It is recommended that the student be working in an Agile environment or has had Agile
training.
